### ISSUE TITLE
Cannot stop PriorityScheduler threads

### ISSUE THREAD

**Issue by wanga7** [tjscience/RoboSharp#105]
The threads launched in PriorityScheduler run forever until my program stops. It would be nice to provide a mechanism to manually stop those threads, or starts them on-demand. Thanks!

**Comment by RFBomb** [comment]
RoboCommand.Stop() should work (as long as you still have the object reference), but Stop() currently has a check for the RunHours property. 

I've wrapped the Stop() command in my helper class so that I set RunHours = null before calling Stop(). This stops the robocopy thread immediately, if it is running. 

Also, my PR #107 has introduced a new property `StopIfDisposing` that should do what you want when set to TRUE. If the RoboCommand object is disposed, and the RoboCopy process is still running, it kills it. 

That said, I'm not using PriorityScheduler right now, so this would have to be verified.

**Comment by wanga7** [comment]
I did some testing locally and here're my conclusions:

1. The problem I mentioned above is not about "roboCommand process" not stopping, but "the task scheduling threads allocated by PriorityScheduler" not stopping until program exits.
2. If you take a look at the PriorityScheduler class you'd see it creates the threads but there's no way to end them.
3. Swapping out the PriorityScheduler with the .Net default one (TaskScheduler.Current) seem to solve the problem.

**Comment by PCAssistSoftware** [comment]
@wanga7 - can you please test again after all the changes made from RFBomb in #107 have been merged and taking into account comments in reply above to see if still an issue?  thank you

**Comment by wanga7** [comment]
See my comment above: it's unrelated to RFBomb's problem and his fix won't solve my problem here.

**Comment by PCAssistSoftware** [comment]
Okay thanks for confirming, feel free to submit a PR if you have a fix then

**Comment by RFBomb** [comment]
Are these threads sitting there consuming resources? Or do you wish to just have them killed off if all RoboCommands have finished executing? Best I can tell, those threads should just be sitting idle if no tasks are scheduled.

**Comment by RFBomb** [comment]
@tjscience , @PCAssistSoftware , @wanga7 I just ran into something peculiar when implementing RoboQueue into my application. It appeared as if RoboQueue was not working properly in my scenario, and I think the PriorityScheduler may be at fault.

My Application queues up 18 RoboCommands, stuffs them into a RoboQueue, then starts them all. First in ListOnly mode, then once they all complete, in copy mode. For List-Only mode, I start all commands at same time, but for copy mode only 1 runs at a time. This is all fine and handled by RoboQueue.

The problem was pausing/cancelling the commands would result in the application hanging due to the RoboCommands return task getting stuck waiting for activation. I think I resolved this in the code itself, but before doing so I tested with `TaskScheduler.Current` as suggested by @wanga7, and the problem went away immediately, before applying my other code changes that affected RoboQueue. 

I believe this occurred because my application is starting 18 robocommands, but due to being a 4-core CPU, the PriorityScheduler only created 4 threads. So I had 18 RoboCommands, each with its own ProgressEstimator, and RoboQueue. Thats something like 30-40 async tasks all running at once, spread across the 4 threads supplied by TaskScheduler. Once cancelled, another RoboQueue was unable to be started until application restart, which refreshes the threads.  

Since dropping Net4.0, everything has been updated to run as Async using `await`, so each of t these tasks shouldn't be blocking the thread anymore, but I still ran into the issue until switching over to `TaskScheduler.Current`. I think that its likely safe to update all the tasks to use that scheduler instead of the PriorityScheduler object. Its also probably better overall to do so, allowing then application to just use the native scheduler and thread pool for managing these tasks,

Thoughts?

**Comment by PCAssistSoftware** [comment]
I would agree with your logic of moving everything over to `TaskScheduler.Current`, now that we have dropped .NET 4.0 and made the most of Async, then this change would make perfect sense to me

**Comment by RFBomb** [comment]
OK, 

#145 has a commit pushed that uses TaskScheduler.Current instead.

**Comment by PCAssistSoftware** [comment]
Is this issue still relevant or is it now solved due to change of using TaskScheduler.Current instead?  If so will close

**Comment by wanga7** [comment]
Solved with the TaskScheduler change.
