### ISSUE TITLE
After change #109: The fixed RoboCopy parameter /BYTE is no longer necessary.

### ISSUE THREAD

**Issue by JoE-Seeve** [tjscience/RoboSharp#111]
Thank you for adjusting the byte conversion in "statistics.cs". However, this adjustment is only necessary if the fixed parameter /BYTE in "RoboCommand.cs" "GenerateParameters" is removed. With this, RoboCopy is asked to return only byte values ​​and a conversion is not necessary.

With the adjustment of the conversion function, the workaround with the fixed parameter /BYTE is no longer necessary (I'm assuming that this is just an old workaround).

Other reasons to remove the fixed parameter /BYTE can be read in #109.

**Comment by PCAssistSoftware** [comment]
Rather than repeat myself yet again - see my response here - https://github.com/tjscience/RoboSharp/issues/109#issuecomment-968351739

I have put some time in my work diary this week to spend a while testing my GUI and other solutions I know of which are using RoboSharp to see what side effects occur (if any) from removing hardcoded /BYTE switch. Will feedback more then.  As per other response perhaps if you can share on here (or privately via email in my profile) your methods for showing file progress then I can compare that with mine which currently doesn't work without /BYTE I believe

**Comment by PCAssistSoftware** [comment]
Closed as per discussion in #109 proving why /BYTES is currently hard coded in
