### ISSUE TITLE
Writing Unit tests

### ISSUE THREAD

**Issue by sophiedaiter** [tjscience/RoboSharp#177]
Hi,
i have a method calling StartAsync which returns RoboCopyResults
i would like to mock startAsync in my unit tests and return different results (for happy flow and fail flow) but RoboCopyResult c'tor is internal. so i can't create an instance of it . 

what can i do? @RFBomb 
Thanks
Sophie

**Comment by RFBomb** [comment]
Sophie,
I don't think any of us considered that scenario when we hid the constructor. It's also why I did a ton of work to the repo trying to support custom implementations of RoboCommand though. So I believe I can guide you in the correct direction here. 

Unfortunately, the work I did in #161 was never merged in, mostly because it's a major re-assessment of the library. But that fork might have what you need. It's what I use in my production project. 

@PCAssistSoftware - I've done a ton of work on #161 and outside it as well. I think it's likely a good time to have a discussion on evaluating it,  and either merging it, putting it out as a secondary package, etc. I'm personally happy with bringing it under my namespace in my GitHub if that's how we want to proceed. Doing it like that keeps the custom implementation logic isolated from this project, and will require just publicizing some of the constructors to accommodate it.

**Comment by PCAssistSoftware** [comment]
Hi Robert, good to hear from you.

Happy to take a look at what you have done and discuss the way forward.  The second option may be the best way perhaps so that we don't impact too much on the existing package, but can decide that once discussed and evaluated, just need to be aware of the many people who use this library and any changes that may affect them, especially as any version number increment we may decide to do at some point will result in an automatic NuGet release etc.

**Comment by RFBomb** [comment]
Yea, that reasoning is exactly why we never merged it in.
Most of the PR is meant to facilitate custom implementations of IRobocommand. I have created several myself, as I'm using it as the backend for a file sync framework I designed for my application (RFBCodeWorks.NetworkSyncObjects). 
I think it may make the most sense to have it just be a secondary nuget package, either contained within this repo, or even an external one. (My personal preference is a new project within this repo, that just builds the secondary package. This would keep it centralized to this repo instead of having to bounce between one the main one and one hosted on my page)

If I recall correctly, most of the additions are static helper methods to help with the evaluation/comparison of file pairs for custom implementations.

I could begin work on that sometime this week or next.

**Comment by PCAssistSoftware** [comment]
That make sense to me and i'm happy to test and evaluate as needed, and we can then decide location as best to see what Terry has to say if around as well.

**Comment by RFBomb** [comment]
Cool, thanks. Shouldn't take too long, all the code is already written. Just gotta make it into a pretty PR

**Comment by sophiedaiter** [comment]
Hi Guys,
Thanks for the quick response.
So do you think we should use the side branch ( #161<https://github.com/tjscience/RoboSharp/pull/161> ) or wait for this new release?

Thanks
Sophie

**Comment by RFBomb** [comment]
@sophiedaiter 
I wouldn't use the branch in #161. That branch had a ton of changes to it that are not yet concrete. Those changes were done for full custom implementations (effectively rewriting robocopy or your own RoboQueue, which my personal project required).

I'm isolating the changes into several smaller commits and doing some reorganizing/renaming/cleaning up as I do it. If you don't need a full custom IRobocomand implementation, I would recommend using the fork from #179, which exposes a constructor for you to use.

**Comment by RFBomb** [comment]
@sophiedaiter 
These changes have been merged into the main branch, so feel free to use that again. A new nuget package likely won't arrive until the Extensions package is complete. 

But little to no changes are anticipated on the Robosharp package as part of that PR.
