### ISSUE TITLE
RoboCommand Dispose code wrong

### ISSUE THREAD

**Issue by zabulus** [tjscience/RoboSharp#178]
We currently experience following exception in finalization code of RoboCommand:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at RoboSharp.RoboCommand.get_IsScheduled()
   at RoboSharp.RoboCommand.Dispose(Boolean disposing)
   at RoboSharp.RoboCommand.Finalize())
```
And looks like RoboCommand dispose is malformed. There is no check for disposing flag https://github.com/tjscience/RoboSharp/blob/dev/RoboSharp/RoboCommand.cs#L891

**Comment by PCAssistSoftware** [comment]
Hi @zabulus - have it in use on a daily basis in several different apps and have never had that error raise, so would need a bit more context as to what you are doing and how / when it is being raised if possible?  Also feel free to submit a PR if you have a suggested fix for it.

**Comment by zabulus** [comment]
We are in process of porting application to net7.0 and run tests on linux. RoboCommand is used in two places with pattern
```
using(var cmd = new RoboCommand())
{
// set options, execute, etc.
}
```
I know that RoboSharp is not supposed to be used in linux, we will disable it. Therefore it's not a blocker issue for our app. 
I've just dived to code and found that there is wrong Dispose(false) method code.
Cause of the issue is exception in ctor caused of missing dll calls in linux invoked in VersionManager.Version property.
On windows this exception could occur in case missing using block/statement for RoboCommand.

**Comment by PCAssistSoftware** [comment]
And that is exactly the way I use RoboCommand in all my apps but in Windows rather than Linux, and as I say have never seen the exception at all.  If can see it happening for myself then I will of course address and fix it.  Thanks for reporting by the way, always appreciated, just need to replicate the error this end so I can find and test a fix for it.

**Comment by RFBomb** [comment]
@zabulus 
- The IsScheduled property checks the `CopyOptions.RunHours` property. The only way that this can throw a `NullReferenceException` is if your robocommand has the CopyOptions set to null, which should never be the case if using any of the provided constructors (but may be the case if your code set the property to null). 

- The disposal code is the way it is, awkward as it may look, for a reason. The finalizer calls `Dispose(false)`, while explicit disposal (such as with a using statement) calls `Dispose(true)`. The reason the block between https://github.com/tjscience/RoboSharp/blob/f61a51e6cc60522f0d7894b2ff9e835072d0120d/RoboSharp/RoboCommand.cs#L890-L894  is written as such is to ensure that if the calling process exits (such as an application fault or user quitting it out), the robocommand will be killed. If that were wrapped into the `if (disposing)` statement, the RoboCopy process would only be killed if explicitly disposed of.

**Comment by RFBomb** [comment]
I reworked the Disposal pattern in #186 to the standard layout. Overall logic is unchanged because its intentional. But, I did ad a null check to IsScheduled, just in case CopyOptions is null ( it should never be null, but in this particular instance its neglibile as i'm just passing it into `string.IsNullOrWhiteSpace` anyway)

**Comment by zabulus** [comment]
On Dispose(false) you can't touch any managed object field, in this case CopyOptions. The same is for Process object as they might be disposed and set to null before call ~RoboCommand().

**Comment by RFBomb** [comment]
Null checks are in place for process object. And that really only applies if the command is being disposed of under unexpected conditions, such as when exiting the application while the task is still executing. Otherwise, the task takes care of process disposal. 

For copy options, if it were finalized by the GC prior to the RoboCommand finalizer being called, yes that may be problematic. But, there is a strong reference here that *should* hold Copy options alive, especially when disposing via a `Using()` statement. 


You are the only person to report this issue. We use this daily without any issues at all. And it passes all unit tests. Submit a PR with a fix and a unit test to resolve that shows failure without the fix it if it's still Problematic.

**Comment by RFBomb** [comment]
A solution to this may be storing IsScheduled into a private field when the command is started, then evaluating that in place of copy options. 

`If (StopIfDisposing && IsRunning && !IsScheduled)`

IsScheduled will property will have to be updated to look at the private field. Which arguably makes more sense than returning true if the command hours were set but it was never started. 

The field should be set false when robocopy exits, since it is no longer running.

**Comment by zabulus** [comment]
Sorry I didn't get around this issue in a while.
> For copy options, if it were finalized by the GC prior to the RoboCommand finalizer being called, yes that may be problematic. But, there is a strong reference here that should hold Copy options alive, especially when disposing via a Using() statement.

the problem is here. From what I've seen the finalizer is called for an object that haven't been properly initialized, I think it's because the finalizer exists at all. So assumption that CopyOptions is alive is not right.
Rule of thumb for finalizer code (dispose(false)) is that you don't touch any reference for managed object, as they might be swept earlier than object currently disposing.

> You are the only person to report this issue. We use this daily without any issues at all. And it passes all unit tests. Submit a PR with a fix and a unit test to resolve that shows failure without the fix it if it's still Problematic.

Unfortunately, I'm unable to reproduce this on unit-test scale with all environment variables (missing entrypoint, net7.0, linux), maybe mstest somehow affects this. I've reported the issue, because:
a) I've experienced crash with the library
b) I've experienced crash in unexpected place (finalizer with, IMO, wrong code)

In this particular case problem is with CopyOptions.RunHours that must be unscheduled. It should be a separate object that tracks this and on dispose(false) unschedules the run. But IMO, it should be designed in another way, but not relevant to the issue. 

So if you think, issue is not worth your time, feel free to close the issue.

**Comment by RFBomb** [comment]
@zabulus 
I've re-read the issue, and I'm currently working with the library at the moment so I can take a look at this.

After a re-review I tend to agree with you and am open to changing the logic for disposal to work around this.

Here are my thoughts for review:
- This situation only occurs due to checking if the process is scheduled, and allows cancelling it. 
- the Boolean property evaluated is actually a proxy for a method that looks at the CopyOptions object (this is the issue). 
- the command isn't actually scheduled until you have started it, making the IsScheduled property misleading. 


As such, my game plan:
- IsScheduled will now be set true/false when the Start() method is called. This should eliminate the reliance on a potentially disposed CopyOptions object, and resolve the issue at hand. 

@PCAssistSoftware / @zabulus 
Can you when you get a chance do some brief testing on the scheduling via RunHours? What I'm most concerned with is whether or not the process itself is still running. (For example, schedule 1/2/5 minutes in the future, does the RoboCommand task stay running while it's idle and waiting for robocopy to print something? Or does it put a request through to windows to start robocopy with specific commands, and the task completed prior to the copy operation being run? - this may even be testable using the BackupApp)

Finally, @zabulus you mentioned you use this library in an app also built for Linux. Obviously RoboCopy is not available there. I am doing some work on the RoboSharp.Extensions package at the moment to work around this concern. I don't have a Linux system to test with. When you get a chance could you. Test that package? My concerns are: currently it imports a method from a kernel32.dll, so I'm not even sure if it will load up at all on Linux. I would like it to have that option, so my intent would be to make generic assemblies then windows-specific assemblies with the native features like CopyFileEx. This would allow you to have an IRoboCommand that can run in Linux, using FileStream to copy the files natively. (In fact that's what I'm currently developing). Let me know if you would be interested in assisting with that testing/have some input on it. Currently it is in development on the PR list

**Comment by PCAssistSoftware** [comment]
@RFBomb 

Hi, just done a quick test of RunHours for you using BackupApp and Single job (RoboCommand)

At 14:45 I started a job with runhours set to 1450-1500

Initially after starting job interface just sits waiting as expected

![image](https://github.com/tjscience/RoboSharp/assets/10872799/ba3af731-5b8d-43bb-a6f8-e5406c1e31aa)

And then at 14:50 it ran the job correctly

![image](https://github.com/tjscience/RoboSharp/assets/10872799/f260b4e7-e70b-423c-878f-269128bc4e1a)

Repeated the test using Multijob (RoboQueue) with run hours of 1455-1500 - clicked start queue at 14:53

![image](https://github.com/tjscience/RoboSharp/assets/10872799/dd4141f3-f7a5-4a94-aa13-eaf30a86b42c)

At 14:55 again it ran successfully

![image](https://github.com/tjscience/RoboSharp/assets/10872799/6ef67a3f-3de8-42fc-bb71-bbec6ede31c5)


Anything else you need me to test just let me know

**Comment by PCAssistSoftware** [comment]
update: also tried adding two jobs to the queue, one **without** runhours and one **with** runhours

Job 1 ran immediately as expected

![image](https://github.com/tjscience/RoboSharp/assets/10872799/c18718fa-c538-4be0-80bf-2aaf99dc1c67)

Job 2 ran at time specified in runhours (1513)

![image](https://github.com/tjscience/RoboSharp/assets/10872799/98a0db8e-ba5e-4121-ad28-8563c5b2d9c8)

**Comment by RFBomb** [comment]
alright this confirms my testing as well. robocopy itself sits idle until that time. If it is started within the allowed time then it starts immediately. 
![image](https://github.com/tjscience/RoboSharp/assets/20431767/bf84468d-70dd-4c08-bf1c-65d48ba88e55)

**Comment by RFBomb** [comment]
Looking at the code within IsScheduled prior to the change, it was already performing a null check. So the call to `String.IsNullOrWhiteSpace` should have had no trouble if the GC collected the CopyOptions (or not created) - It would have seen that the object was null, passed null into the method, then been fine. So I'm still very confused by this issue.

> We are in process of porting application to net7.0 and run tests on linux. RoboCommand is used in two places with pattern
> 
> ```
> using(var cmd = new RoboCommand())
> {
> // set options, execute, etc.
> }
> ```
> 
> I know that RoboSharp is not supposed to be used in linux, we will disable it. Therefore it's not a blocker issue for our app. I've just dived to code and found that there is wrong Dispose(false) method code. **Cause of the issue is exception in ctor caused of missing dll calls in linux invoked in VersionManager.Version property**. On windows this exception could occur in case missing using block/statement for RoboCommand.

This is where you would want to use a custom implementation of IRoboCommand, which is what the Extensions package is aimed at. I'm currently working on implementation designed around this in fact.

**Comment by RFBomb** [comment]
@PCAssistSoftware @zabulus 

The changes to resolve this are located over in #196, which should be ready for testing.

This should now allow instantiating a RoboCommand within a Linux environment (more specifically, CopyOptions relied on VersionManager, which has been resolved). Note that attempting to Start() the RoboCommand will throw a PlatformNotSupportedException. But now that CopyOptions can be instantiated, a custom cross platform IRobocommand can be created.  

This also resolves the concern with the Parser and empty source/destination strings.

**Comment by PCAssistSoftware** [comment]
@RFBomb - excellent, will find some time tomorrow PM (UK time) to test and feedback

**Comment by PCAssistSoftware** [comment]
@RFBomb - found some time this evening to start testing.

P.S. Other than testing my reported parser issue (which now seems to working, thanks!), what else do you want me to test for, as I have never encountered the original reported issue myself (or to be honest did I fully understand it anyway), so any pointers on what I can test to replicate it?

**Comment by RFBomb** [comment]
So I believe the issue @zabulus was encountering was actually due to creating a RoboCommand from a Linux app, so to test this it would actually have to be run within a Linux app/environment. The DLLs being used to detect windows version (and thus supported robocopy options) will obviously not work since Linux doesn't have Kernel32.dll. 

What I wrote is some basic fallback functionality so that the Windows-only code is not called during CopyOptions initialization (which was only used to set a string for default directory attributes). Functions that require it now throw exceptions if not running in a windows environment. 

So the only way to test these would be to do so within a Linux environment. At the moment I don't have a way to run that, and I don't have an app that is cross-platform to test with. (I also don't know if it's something we could potentially test via AppVeyor, as I believe that can specify specialized environments, but I haven't dug that deep to know yet). Ideally we would have unit tests, but again, they have to be run within Linux environment.

**Comment by PCAssistSoftware** [comment]
Okay thanks for explaining, make sense now.  Unfortunately I don't have a linux environment to test with either so probably limited to what I can do in relation to that, but I can test the PR in my current apps to ensure all working okay generally and that none of the changes have had any effect etc.  I will do this tomorrow.  Hopefully @zabulus can do some testing in relation to Linux for us

**Comment by RFBomb** [comment]
That's what my hope was as well. 
As far as testing is concerned, it should be simple enough: just create a new RoboCommand using the `using` statement as he did before. This part Should succeed just fine (this is where it previously failed). Now it should fail with a `PlatformNotSupported` exception when `Start()` is called. 

If that is the case, then it is working as intended. (The object itself isn't the problem, as it can still be used for serialization. But attempting to run it will fail, so that is when the exception is thrown.)

But it should now be able to initialize and dispose properly in a Linux environment.

**Comment by PCAssistSoftware** [comment]
@RFBomb - done all the testing I can e.g. parse issue (confirm fixed) and just general testing of changes to make sure no other effects and all is working fine, so really is over to @zabulus for linux testing and feedback

**Comment by PCAssistSoftware** [comment]
@RFBomb  - Tempted to merge this in anyway as doesn't look like @zabulus is going to test, and I assume you are happy with it?

**Comment by zabulus** [comment]
Sorry, I've took a look for changes, LGTM. Thank you!
