### ISSUE TITLE
Send an robo options at the run time

### ISSUE THREAD

**Issue by saeid64** [tjscience/RoboSharp#18]
Hi,
Great and very useful wrapper, thank you for sharing.
However, is there any way to send the robocopy options as a string? I want to choose robo options at the runtime.
Thanks

**Comment by tjscience** [comment]
Hi, I am glad you like RoboSharp! Currently there is no way to do what you are asking and this is not something that we would implement. Not because it is not a good feature, but because it is outside of the scope of the project. The whole purpose of RoboSharp is providing a c# wrapper for robocopy. However, what you are asking for is exactly what robocopy already does. In your case, I would simply use robocopy. You can start a process in c# and simply pass the arguments as a string. If you really want to do this with RoboSharp, I would recommend forking the project and implementing it on your own. The change would not be very difficult. You could simply inject your own logic to provide a custom argument string in RoboCommand, and if present, use that instead of the output from GenerateParameters(). This is all in the RoboCommand.Start() method. Thanks for the interest!
