### ISSUE TITLE
Why RoboSharp does not support net 4.0 ?

### ISSUE THREAD

**Issue by odysseus1973** [tjscience/RoboSharp#37]
Hello!

Why RoboSharp does not support net 4.0 ?

Thanks!

**Comment by tjscience** [comment]
In an effort to stay consistent with latest major releases of the .NET framework, Robosharp is built on .NET 4.5. We will be moving to 4.6 soon to take advantage of some of the performance enhancements. 

That being said, it is pretty easy to build the source code using a 4.0 as the target platform. I believe that the only thing you would need to change are mentions of Task.Run since that does not exist in 4.0.

I have attached a copy of RoboSharp built against 4.0 for your convenience (Just unzip it).
[RoboSharp.zip](https://github.com/tjscience/RoboSharp/files/1629684/RoboSharp.zip)

**Comment by odysseus1973** [comment]
Thank you. Yes, I can compile the sources for .Net 4, but what I missing is the support of the Nuget and the updates.
