### ISSUE TITLE
Robosharp can't work when WMI is corrupted

### ISSUE THREAD

**Issue by rshaporenko** [tjscience/RoboSharp#84]
Why don't to use Environment.OSVersion Property instead of WMI query SELECT * FROM Win32_OperatingSystem inside VersionManager class. Sometime that query is failed due to WMI corrupted. Environment.OSVersion should be less vulnerable way.

Thank you

---- to fix WMI corruption I have to execute below script, but I wold avoid WMI dependency
cd %windir%\system32\wbem
for /f %%s in ('dir /s /b *.mof *.mfl') do mofcomp %%s

**Comment by tjscience** [comment]
We do not use the property from the environment class because Microsoft states that you should not: 

> "The Environment.OSVersion property does not provide a reliable way to identify the exact operating system and its version."

https://docs.microsoft.com/en-us/dotnet/api/system.environment.osversion?view=netframework-4.8

WMI is the most reliable way to obtain the information RoboSharp needs, but there can be issues with WMI. The easiest way to troubleshoot those issues is running WBEMTEST.

**Comment by wingers999** [comment]
As perhaps a fallback option (or) instead of WMI you could use My.Computer.Info.OSFullName?

**Comment by tjscience** [comment]
I am not familiar with that property. Looking it up quickly it looks like VB only, is that correct? Also, this seems to use WMI under the covers anyway.

**Comment by wingers999** [comment]
Yes, sorry you are right - my mistake

Another solution I use in one of my apps, is I check WMI and if that check fails then I check registry, at least one way or another it then gets information it needs - look under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion

**Comment by tjscience** [comment]
I am working on making this better...

**Comment by tjscience** [comment]
I have added a better way to check the OS version here using RtlGetVersion in ntdll.dll. I have also kept the option to use WMI as a fallback and you can now manage the method used by setting the VersionManager.VersionCheck property whose value is an enum. Committed this to `dev` branch since most current work at the moment is being done in there. Please test it out when you get a chance.

**Comment by wingers999** [comment]
Excellent - works perfectly for me

**Comment by Xinnony** [comment]
Not work for me lastday, i have error line 42 in VersionCheck: `return version.Value;`
I fix this but today i try with original version and now is work... hum...
